package prompt

//go:generate go run gen_prompts.go

// content maps prompt name to its stripped SKILL.md body.
// Populated by content_generated.go (generated by go:generate).
var content map[string]string
