//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	skillsDir := filepath.Join("..", "skills")

	entries, err := os.ReadDir(skillsDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to read skills dir: %v\n", err)
		os.Exit(1)
	}

	// Collect skill names
	var names []string
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		skillFile := filepath.Join(skillsDir, entry.Name(), "SKILL.md")
		_, err := os.Stat(skillFile)
		if err != nil {
			continue
		}
		names = append(names, entry.Name())
	}

	// Only embed pipeline step skills in the binary. Orchestrator skills
	// (sherpy-cli-planner, sherpy-flow) and meta skills reference the
	// pipeline steps but are not themselves pipeline steps, so they
	// don't need to be embedded. This prevents "orphaned content" warnings
	// during test runs.
	skipList := map[string]bool{
		"sherpy-cli-planner":              true, // Orchestrator skill
		"sherpy-cli":                      true, // Meta skill
		"sherpy-flow":                     true, // Orchestrator skill
		"implementation-plan-best-practices": true, // Meta/reference skill
		"create-continuation-prompt":      true, // Utility skill
		"contracted":                      true, // Non-pipeline skill
	}

	// Filter names
	var filtered []string
	for _, name := range names {
		if !skipList[name] {
			filtered = append(filtered, name)
		}
	}
	names = filtered

	sort.Strings(names)

	// Build the generated file
	var buf bytes.Buffer
	buf.WriteString("// Code generated by gen_prompts.go. DO NOT EDIT.\n")
	buf.WriteString("//go:build !ignore_autogenerated\n\n")
	buf.WriteString("package prompt\n\n")
	buf.WriteString("func init() {\n")
	buf.WriteString("\tcontent = map[string]string{\n")

	for _, name := range names {
		skillFile := filepath.Join(skillsDir, name, "SKILL.md")
		data, err := os.ReadFile(skillFile)
		if err != nil {
			fmt.Fprintf(os.Stderr, "failed to read %s: %v\n", skillFile, err)
			os.Exit(1)
		}
		body := stripFrontmatter(string(data))
		buf.WriteString(fmt.Sprintf("\t\t%q: %q,\n", name, body))
	}

	buf.WriteString("\t}\n}\n")

	if err := os.WriteFile("content_generated.go", buf.Bytes(), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "failed to write generated file: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated content_generated.go with %d prompts\n", len(names))
}

// stripFrontmatter removes YAML frontmatter from the beginning of content.
// This is a copy of prompt.StripFrontmatter - we can't import the prompt
// package here because this generator runs before the package is built.
func stripFrontmatter(content string) string {
	content = strings.TrimSpace(content)

	if !strings.HasPrefix(content, "---") {
		return content
	}

	rest := content[3:]
	if len(rest) > 0 && rest[0] != '\n' {
		return content
	}

	idx := strings.Index(rest, "\n---")
	if idx == -1 {
		return content
	}

	after := rest[idx+4:]
	if len(after) > 0 && after[0] != '\n' && after[0] != '\r' {
		return content
	}

	body := rest[idx+4:]
	return strings.TrimSpace(body)
}
