package spec

//go:generate go run gen_specs.go

// content maps document type to its specification markdown body.
// Populated by content_generated.go (generated by go:generate).
var content map[string]string
