//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
)

// specSources maps document types to their specification files, relative to
// docs/specifications/. The mapping is explicit because some document types
// do not share a directory name with their spec (e.g. the "gap-analysis"
// document type lives under gap-analysis-worksheet/spec.md). Only document
// types that have a formal spec.md are listed here.
var specSources = []struct {
	docType string
	relPath string
}{
	{"business-requirements", "business-requirements/spec.md"},
	{"technical-requirements", "technical-requirements/spec.md"},
	{"milestones", "milestones/spec.md"},
	{"milestone-tasks", "milestone-tasks/spec.md"},
	{"timeline", "timeline/spec.md"},
	{"qa-test-plan", "qa-test-plan/spec.md"},
	{"gap-analysis", "gap-analysis-worksheet/spec.md"},
}

func main() {
	specsDir := filepath.Join("..", "docs", "specifications")

	var buf bytes.Buffer
	buf.WriteString("// Code generated by gen_specs.go. DO NOT EDIT.\n")
	buf.WriteString("//go:build !ignore_autogenerated\n\n")
	buf.WriteString("package spec\n\n")
	buf.WriteString("func init() {\n")
	buf.WriteString("\tcontent = map[string]string{\n")

	for _, s := range specSources {
		src := filepath.Join(specsDir, s.relPath)
		data, err := os.ReadFile(src)
		if err != nil {
			fmt.Fprintf(os.Stderr, "failed to read %s: %v\n", src, err)
			os.Exit(1)
		}
		buf.WriteString(fmt.Sprintf("\t\t%q: %q,\n", s.docType, string(data)))
	}

	buf.WriteString("\t}\n}\n")

	if err := os.WriteFile("content_generated.go", buf.Bytes(), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "failed to write generated file: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated content_generated.go with %d specs\n", len(specSources))
}
